---
title: "orb path analysis test 4"
output:
  pdf_document: default
  html_document: default
date: "2023-05-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

#read in data
orbpath <- read.csv("orb_path.csv")
eyepath <- read.csv("cleaned.csv")

orbpath <- orbpath %>%
  rename(time = time..seconds.)
eyepath <- eyepath %>%
  rename(time = time..milliseconds.)

combined <- eyepath %>%
  inner_join(orbpath, by = "time", suffix = c("_eye", "_orb"))

combined <- combined %>%
  mutate(time = time - 1683076323472)

combined
```

```{r}
xComp <- ggplot(combined, aes(x = time, y = x_orb)) +
  geom_line(aes(x = time, y = x_eye, color = "Eye"), size = 1) + 
  geom_line(aes(x = time, y = x_orb, color = "Orb"), size = 1) +
  labs(x = "time in ms", y = "horizontal component") +
  scale_x_continuous(breaks = seq(0, 4000, by = 400))
  


yComp <- ggplot(combined, aes(x = time, y = y_orb)) +
  geom_line(aes(x = time, y = y_eye, color = "Eye"), size = 1) + 
  geom_line(aes(x = time, y = y_orb, color = "Orb"), size = 1) +
  labs(x = "time in ms", y = "vertical component") + 
  scale_x_continuous(breaks = seq(0, 4000, by = 400))

xComp
yComp
```

